# Generated by Django 6.0 on 2025-12-23 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], max_length=20)),
                ('service_interest', models.CharField(choices=[('customer-service', 'Customer Service Staffing'), ('back-office', 'Back-Office & Administrative Support'), ('finance', 'Finance & Accounting'), ('digital-marketing', 'Digital Marketing Staffing'), ('it-solutions', 'IT & Technology Solutions'), ('data-analytics', 'Data Analytics Services'), ('multiple', 'Multiple Services'), ('custom', 'Custom Solution')], max_length=100)),
                ('requirements', models.TextField(blank=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for the sales team')),
            ],
            options={
                'verbose_name_plural': 'Consultation Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('service_interest', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('service_type', models.CharField(choices=[('single-service', 'Single Service'), ('multiple-services', 'Multiple Services'), ('custom-solution', 'Custom Solution')], default='single-service', max_length=50)),
                ('team_size', models.CharField(choices=[('1-5', '1-5 team members'), ('6-10', '6-10 team members'), ('11-20', '11-20 team members'), ('20+', '20+ team members')], max_length=20)),
                ('additional_requirements', models.TextField(blank=True)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('specific_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.service')),
            ],
            options={
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
