# Generated by Django 6.0 on 2025-12-23 16:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_consultationrequest_contactsubmission_serviceinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', ckeditor.fields.RichTextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('services', 'Services'), ('pricing', 'Pricing'), ('contact', 'Contact'), ('technical', 'Technical'), ('process', 'Process')], default='general', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'category'],
            },
        ),
    ]
