# Generated by Django 6.0 on 2025-12-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_notificationmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationMessage',
        ),
    ]
