# Generated by Django 6.0 on 2025-12-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_abouthero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact ServiceLink BPO', max_length=200)),
                ('subtitle', models.TextField(default="Get in touch with our expert team. We're here to help you streamline your business operations.")),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Hero Sections',
            },
        ),
    ]
