# Generated by Django 6.0 on 2025-12-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contacthero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('list', 'Services List Page'), ('detail', 'Service Detail Page')], default='list', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='service_hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Service Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetailHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=200)),
                ('custom_subtitle', models.TextField(blank=True)),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='service_detail_hero/')),
                ('show_default', models.BooleanField(default=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='website.service')),
            ],
            options={
                'verbose_name_plural': 'Service Detail Heroes',
            },
        ),
    ]
